namespace TeaPie.Helpers;

// This code was generated by ChatGPT 4o
internal static class PathHelper
{
    public static string TrimRootPath(this string fullPath, string rootPath, bool keepRootFolder = false)
    {
        // Normalize both paths to ensure consistent comparison and manipulation
        var normalizedFullPath = Path.GetFullPath(fullPath).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        var normalizedRootPath = Path.GetFullPath(rootPath).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);

        // Check if the full path starts with the root path
        if (normalizedFullPath.StartsWith(normalizedRootPath, StringComparison.OrdinalIgnoreCase))
        {
            if (keepRootFolder)
            {
                // Return everything from the last occurrence of the root folder (including it)
                return normalizedFullPath[(normalizedRootPath.LastIndexOf(Path.DirectorySeparatorChar) + 1)..];
            }
            else
            {
                // Use Path.GetRelativePath for efficient trimming without root folder
                return Path.GetRelativePath(normalizedRootPath, normalizedFullPath);
            }
        }

        return fullPath; // Return as is if rootPath is not at the start
    }
}
