# @name RentCarRequest
POST {{ApiBaseUrl}}{{ApiCarRentalSection}}
Content-Type: application/json
// Variables and even functions can also be used in the body definition

{
    "Id": 42,
    "CarId": {{NewCarId}},
    "CustomerId": {{NewCustomerId}},
    "RentalStart": "{{$now "yyyy-MM-dd"}}",
    "RentalEnd": "{{$carReturnDate {{RentalDays}}}}",
    "Price": 200.00,
    "Notes": "Rented for a weekend wedding.",
    "NumberOfDrivers": 1
}

###
## RETRY-UNTIL-STATUS: [200]
# @name GetCarRentRequest
GET {{ApiBaseUrl}}{{ApiCarRentalSection}}/{{RentCarRequest.request.body.$.Id}}
###

# Example of all available retry directives. Selected RETRY-STRATEGY must be registered first (via script, see 'demo/init.csx').
# - RETRY-UNTIL-STATUS adds a condition specifying until which status codes retrying should continue.
# - Other retry directives override specific properties of the selected retry strategy.
# - If no retry strategy is explicitly selected, default strategy (possibly overriden by other directives) is used.

## RETRY-STRATEGY: Custom retry
## RETRY-MAX-ATTEMPTS: 5
## RETRY-BACKOFF-TYPE: Linear
## RETRY-MAX-DELAY: 00:00:03
## RETRY-UNTIL-STATUS: [200, 201]
# @name GetCarRequest
GET {{ApiBaseUrl}}{{ApiCarsSection}}/{{RentCarRequest.request.body.$.CarId}}
