name: Build and Test PR

# Trigger
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    # Install dependencies
    - name: Install dependencies
      run: dotnet restore

    # Build the project
    - name: Build project
      run: dotnet build --configuration Release --no-restore -warnaserror

    # Run unit tests
    - name: Run Unit tests
      run: dotnet test --no-build --verbosity normal --configuration Release

  validate-test-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload JUnit XML Report
        uses: dorny/test-reporter@v1
        with:
          name: JUnit XML Validation Test
          path: 'demo/demo-report.xml'
          reporter: java-junit
