name: Build and Test PR

# Trigger
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    # Install dependencies
    - name: Install dependencies
      run: dotnet restore

    # Build the project
    - name: Build project
      run: dotnet build --configuration Release --no-restore -warnaserror

    # Run unit tests
    - name: Run Unit tests
      run: dotnet test --no-build --verbosity normal --configuration Release

  publish-docs:
    - name: Generate Documentation with DocFX
      uses: dotnet/docfx-action@v1
      with:
        args: docs/docfx.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site
